baseURL = "https://webmeshproj.github.io/"
languageCode = 'en-us'
title = 'Webmesh Project'
theme = "hugo-geekdoc"

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
  tag = "tags"

[params]
  authorName = "Webmesh Project"
  email = "test"
  geekdocRepo = "https://github.com/webmeshproj/webmeshproj.github.io"
  geekdocDarkModeDim = true

[params.geekdocContentLicense]
  name = "Apache License 2.0"
  link = "https://www.apache.org/licenses/LICENSE-2.0"
