name: Publish to GitHub Pages
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Public Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Build
        run: make

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: github-pages
          path: ${{ github.workspace }}/public/

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
